### ISSUE TITLE
Making a blog.

### ISSUE THREAD

**Issue by TechnoAyan** [mozillakolkata/mozillakolkata.github.io#11]
Why not we make a blog of Mozilla Kolkata itself rather than tagging others blog here?
what say @debloper @swarnava @birajkarmakar @anistark

**Comment by dbbhattacharya** [comment]
In yesterday's meeting we have decided to create a blog so that we can have all the important updates in a single document.

**Comment by TechnoAyan** [comment]
Thats cool.. But what I am talking about is making of a blog which will be part of this website.. host it in github and do the other procedures..

**Comment by dbbhattacharya** [comment]
trust me, we thought exactly in the same way ;)

**Comment by TechnoAyan** [comment]
Cool then. We have to look forward to it.. as soon as possible.. and let me know regarding hosting and other github purposes.. :)

**Comment by swarnava** [comment]
Creating a blog is not that hard github. The issue is actually *purpose*

**Comment by TechnoAyan** [comment]
Yes it is.. but someone has to maintain that blog.. @birajkarmakar proposed me this thing.. I issued it here.. :)

**Comment by birajkarmakar** [comment]
Purpose is there. In our last community meetup, we decided that in every month we will publish our blog on our activities with other related stuffs.  
>Creating a blog is not that hard github. The issue is actually *purpose*

**Comment by TechnoAyan** [comment]
thats cool actually.. but the question lies "Will it be maintained? "

**Comment by birajkarmakar** [comment]
yes, I will assign that role to one community member

**Comment by anistark** [comment]
Should be simple enough.. Given jekyll and github pages.

**Comment by anistark** [comment]
Should be simple enough given jekyll and github hosting.  
|   |
| 
| Kumar Anirudhaabout.me/kumaranirudha |
|  |

   |
|   |

 


     On Monday, 31 August 2015 2:35 PM, birajkarmakar <notifications@github.com> wrote:
   

 yes, I will assign that role to one community member—

**Comment by TechnoAyan** [comment]
yes as @anistark said jekyll is the best option.. :)

**Comment by birajkarmakar** [comment]
Ok so who will help you to set up this?

**Comment by RCMainak** [comment]
This is a wonderful idea. jekyII is probably the easiest way to create a blog.

**Comment by TechnoAyan** [comment]
Maybe Sumantro or @anistark can help me out with the jekyll part.. I will take care of the hosting... :)

**Comment by birajkarmakar** [comment]
Sorry If I am not wrong, there is no hosting part, we have to do all those in hub. For blogging one would sent one blog in text format. We have to merge it. That's it !

**Comment by TechnoAyan** [comment]
ohh yes, my mistake.. We have to merge it with this page that's all.. Now who make the blog and do the maintanance?

**Comment by birajkarmakar** [comment]
Anyone from our community who is interested, can take that.

**Comment by anistark** [comment]
Sure, I can help out setting up the blog..

**Comment by anistark** [comment]
For blogging, we'll ask people to send in markdown format file, via PR, and after reviewing, we can merge it like @birajkarmakar said..

**Comment by birajkarmakar** [comment]
@anistark please proceed! 

I will assign one guy who will write every month activities as blog.

**Comment by anistark** [comment]
Sure @birajkarmakar :+1:

**Comment by TechnoAyan** [comment]
@birajkarmakar If anything needed I can be the blog writer on behalf of the community.. :)

**Comment by birajkarmakar** [comment]
@TechnoAyan yes you can, but as far as you are here in kolkta, how you can track the updates. That's only the problem. Hope you understand it.

**Comment by RCMainak** [comment]
@birajkarmakar @TechnoAyan I think it'll be wise to assign one person to review and update the blog post. Allow all members to write blog post. In that way, if someone gets busy others can continue to write blog post and the blog will be updated. It is not possible for one person to keep track of everything in the community (Just a thought).

**Comment by anistark** [comment]
@RCMainak :+1:

**Comment by birajkarmakar** [comment]
@RCMainak you are right! Initially one guy would be there but we always love to help.
