### ISSUE TITLE
Time to Make a gallery

### ISSUE THREAD

**Issue by ping2ayan** [mozillakolkata/mozillakolkata.github.io#12]
We need a gallery to save all the photos we capture in the time of events..
You can say that as a memory.. or as a proof or maybe you can download those photos from here whenever you want.

Comments needed @debloper @swarnava @anistark @birajkarmakar

**Comment by anistark** [comment]
@TechnoAyan Github introduced [Large File system](https://github.com/blog/1986-announcing-git-large-file-storage-lfs) Check it out.. Though that's not required for this.. Just provide links from flickr should be enough.

**Comment by TechnoAyan** [comment]
yea saw that.. @birajkarmakar upload in flickr ASAP..
