### ISSUE TITLE
Outdated Content on homepage

### ISSUE THREAD

**Issue by RCMainak** [mozillakolkata/mozillakolkata.github.io#16]
![alt text](http://i1379.photobucket.com/albums/ah158/jockr2/mozillakolkataWebsite_zps8b90rfa3.png "Mozilla Kolkata Homepage")

As discussed in telegram the portion in above image is outdated and should be updated. Now the question is which one should be replaced by which one in that portion. In my opinion Developer Edition should stay because this is important and ongoing project. Firefox Hello comes with Firefox in-built (as far as I know) so there is no point putting it up there. I'm not sure about the status of Appmaker. In my limited knowledge it is not a successful project and Mozilla may have abandoned it. 

We can add testpilot and other important thing there. Please suggest what can be added and which is should be replaced. Everyone's opinion counts :tongue: 

Also please correct me if I have provided any wrong info.

**Comment by TechnoAyan** [comment]
Change the whole thing if you want! On 1st June, get to know what are things Mozilla is concentrating now, and make them highlighted on the very first page like - Connected Device, Campus Campaign and many more!
