### ISSUE TITLE
Remove Firefox Hello from homepage

### ISSUE THREAD

**Issue by RCMainak** [mozillakolkata/mozillakolkata.github.io#17]
Firefox Hello will be discontinued in Firefox 49. For further details check <a href="https://support.mozilla.org/en-US/kb/hello-status">this link</a>.

**Comment by RCMainak** [comment]
@swarnava Can you close this one please since it's fixed on PR #18. Also Kindly checkout the issue #19.

**Comment by swarnava** [comment]
Done
